In [ ]:
import numpy as np
import pandas as pd
from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
import os
import requests
from bs4 import BeautifulSoup
import time
import json

In [ ]:
seed_list = pd.read_excel(folder_path + 'Seed list_Research_The Best Cities and States for High-Paying Entry-Level Jobs.xlsx')

In [ ]:
seed_list = seed_list.drop_duplicates(subset=['City', 'State']).reset_index(drop=True)

In [ ]:
seed_list

              City          State
0    New York City       New York
1      Los Angeles     California
2          Chicago       Illinois
3          Houston          Texas
4          Phoenix        Arizona
..             ...            ...
278      Arlington       Virginia
279       Bellevue     Washington
280       Wheeling  West Virginia
281         Racine      Wisconsin
282   Rock Springs        Wyoming

[283 rows x 2 columns]

# Read median graduate salaries data

In [ ]:
df_1 = pd.read_csv(folder_path + 'ACSST1Y2022.S1501-Data_p1.csv', header=1)

In [ ]:
columns_to_keep = ['Estimate!!Total!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Bachelor\'s degree',
                   'Geographic Area Name']
df_1 = df_1[columns_to_keep]

In [ ]:
df_2 = pd.read_csv(folder_path + 'ACSST1Y2022.S1501-Data_p2.csv', header=1)
df_2 = df_2[columns_to_keep]

In [ ]:
df = pd.concat([df_1, df_2])

In [ ]:
df = df.drop_duplicates(subset=['Geographic Area Name'])

In [ ]:
df['City'] = df['Geographic Area Name'].apply(lambda x: x.split(',')[0].replace(' County', '').replace(' township', '').replace(' city', '').replace(' CDP', '').replace(' municipality', '').replace(' town', '').replace(' (balance)', '').replace(' urban county', '').replace(' metro government', '').replace(' metropolitan government', ''))

In [ ]:
df['State'] = df['Geographic Area Name'].apply(lambda x: x.split(',')[-1].strip())

In [ ]:
df.columns = ['median_earnings', 'area_name', 'city', 'state']

In [ ]:
new_row = {'median_earnings': 58526, 'area_name': 'Laramie County, Wyoming', 'city': 'Laramie', 'state': 'Wyoming'}
df = df.append(new_row, ignore_index=True)

In [ ]:
# Laramie County, Wyoming 58,526

In [ ]:
df.city.unique()

array(['Grand Forks', 'Edison', 'Birmingham', 'Mobile', 'Montgomery',
       'Tuscaloosa', 'Fayetteville', 'Fort Smith', 'Jonesboro',
       'Springdale', 'Fort Collins', 'Lakewood', 'Hartford', 'New Haven',
       'Stamford', 'Waterbury', 'Atlanta', 'Columbus', 'Savannah',
       'Caldwell', 'Idaho Falls', 'Meridian', 'Nampa', 'Aurora', 'Joliet',
       'Naperville', 'Rockford', 'Carmel', 'Evansville', 'South Bend',
       'Cedar Rapids', 'Davenport', 'Iowa City', 'Sioux City',
       'Kansas City', 'Olathe', 'Overland Park', 'Topeka',
       'Bowling Green', 'Baton Rouge', 'Lafayette', 'Lake Charles',
       'Shreveport', 'Columbia', 'Germantown', 'Silver Spring', 'Waldorf',
       'Cambridge', 'Lowell', 'Springfield', 'Worcester', 'Ann Arbor',
       'Grand Rapids', 'Sterling Heights', 'Warren', 'Bloomington',
       'Duluth', 'Rochester', 'St. Paul', 'Gulfport', 'Independence',
       'St. Louis', 'Missoula', 'Paradise', 'Nashua', 'Elizabeth',
       'Paterson', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Syracuse',
       'Yonkers', 'Bismarck', 'Akron', 'Broken Arrow', 'Edmond', 'Norman',
       'Eugene', 'Gresham', 'Hillsboro', 'Salem', 'Allentown', 'Erie',
       'Reading', 'Cranston', 'Pawtucket', 'Providence', 'Warwick',
       'Charleston', 'Mount Pleasant', 'North Charleston', 'Rock Hill',
       'Rapid City', 'Sioux Falls', 'Chattanooga', 'Clarksville',
       'Knoxville', 'Orem', 'Provo', 'Salt Lake City', 'West Jordan',
       'West Valley City', 'Arlington', 'Bellevue', 'Tacoma', 'Vancouver',
       'Green Bay', 'Kenosha', 'Racine', 'Cheyenne', 'Honolulu',
       'Chesapeake', 'Norfolk', 'Huntsville', 'Anchorage', 'Chandler',
       'Gilbert', 'Glendale', 'Mesa', 'Phoenix', 'Scottsdale', 'Tucson',
       'Little Rock', 'Anaheim', 'Bakersfield', 'Chula Vista', 'Fresno',
       'Irvine', 'Long Beach', 'Los Angeles', 'Oakland', 'Riverside',
       'Sacramento', 'San Bernardino', 'San Diego', 'San Francisco',
       'San Jose', 'Santa Ana', 'Stockton', 'Colorado Springs', 'Denver',
       'Bridgeport', 'Wilmington', 'Washington', 'Jacksonville', 'Miami',
       'Orlando', 'Port St. Lucie', 'St. Petersburg', 'Tampa',
       'Boise City', 'Chicago', 'Fort Wayne', 'Indianapolis',
       'Des Moines', 'Wichita', 'Lexington-Fayette',
       'Louisville/Jefferson', 'New Orleans', 'Portland', 'Baltimore',
       'Boston', 'Detroit', 'Minneapolis', 'Jackson', 'Billings',
       'Lincoln', 'Omaha', 'Henderson', 'Las Vegas', 'North Las Vegas',
       'Reno', 'Manchester', 'Jersey City', 'Newark', 'Albuquerque',
       'Buffalo', 'New York', 'Charlotte', 'Durham', 'Greensboro',
       'Raleigh', 'Winston-Salem', 'Fargo', 'Cincinnati', 'Cleveland',
       'Toledo', 'Oklahoma City', 'Tulsa', 'Philadelphia', 'Pittsburgh',
       'Memphis', 'Nashville-Davidson', 'Austin', 'Corpus Christi',
       'Dallas', 'El Paso', 'Fort Worth', 'Frisco', 'Garland', 'Houston',
       'Irving', 'Laredo', 'Lubbock', 'Plano', 'San Antonio', 'Richmond',
       'Virginia Beach', 'Seattle', 'Spokane', 'Madison', 'Milwaukee',
       'Laramie'], dtype=object)

In [ ]:
df['30% of monthly salary'] = df.median_earnings.apply(lambda x: (x*0.3)/12)

In [ ]:
df = pd.read_excel(folder_path + 'Seedlist with links.xlsx')

In [ ]:
df['general_url'] = df['url'].apply(lambda x: x.split('?searchQueryState')[0])

In [ ]:
df.url[0].split('?searchQueryState')[0]

'https://www.zillow.com/grand-forks-nd/rentals/'

In [ ]:
df = pd.read_csv(folder_path + 'df.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   median_earnings        222 non-null    int64
 1   area_name              222 non-null    object
 2   city                   222 non-null    object
 3   state                  222 non-null    object
 4   30% of monthly salary  222 non-null    float64
 5   url                    222 non-null    object
 6   general_url            222 non-null    object
 7   rentals_number         222 non-null    float64
dtypes: float64(2), int64(1), object(5)
memory usage: 14.0+ KB

In [ ]:
df

,median_earnings,area_name,city,state,30% of monthly salary,url,general_url,rentals_number
0,51320,"Grand Forks County, North Dakota",Grand Forks,North Dakota,1283.000,https://www.zillow.com/grand-forks-nd/rentals/...,https://www.zillow.com/grand-forks-nd/rentals/,104.0
1,80096,"Edison township, Middlesex County, New Jersey",Edison,New Jersey,2002.400,https://www.zillow.com/edison-nj/rentals/?sear...,https://www.zillow.com/edison-nj/rentals/,82.0
2,48837,"Birmingham city, Alabama",Birmingham,Alabama,1220.925,https://www.zillow.com/birmingham-al/rentals/?...,https://www.zillow.com/birmingham-al/rentals/,775.0
3,51468,"Mobile city, Alabama",Mobile,Alabama,1286.700,https://www.zillow.com/mobile-al/rentals/?sear...,https://www.zillow.com/mobile-al/rentals/,264.0
4,47376,"Montgomery city, Alabama",Montgomery,Alabama,1184.400,https://www.zillow.com/montgomery-al/rentals/?...,https://www.zillow.com/montgomery-al/rentals/,463.0
...,...,...,...,...,...,...,...,...
217,90159,"Seattle city, Washington",Seattle,Washington,2253.975,https://www.zillow.com/seattle-wa/rentals/?sea...,https://www.zillow.com/seattle-wa/rentals/,2748.0
218,60547,"Spokane city, Washington",Spokane,Washington,1513.675,https://www.zillow.com/spokane-wa/rentals/?sea...,https://www.zillow.com/spokane-wa/rentals/,517.0
219,65242,"Madison city, Wisconsin",Madison,Wisconsin,1631.050,https://www.zillow.com/madison-wi/rentals/?sea...,https://www.zillow.com/madison-wi/rentals/,474.0
220,54654,"Milwaukee city, Wisconsin",Milwaukee,Wisconsin,1366.350,https://www.zillow.com/milwaukee-wi/rentals/?s...,https://www.zillow.com/milwaukee-wi/rentals/,1011.0
221,58526,"Laramie County, Wyoming",Laramie,Wyoming,1463.150,https://www.zillow.com/laramie-wy/rentals/?sea...,https://www.zillow.com/laramie-wy/rentals/,55.0

# Scrape data

In [ ]:
username = ""
password = ""
proxy = ""
proxy_auth = "{}:{}@{}".format(username, password, proxy)
proxies = {"http": "http://{}".format(proxy_auth)}

In [ ]:
headers = '''
'''.strip().split('\n')

dict_header = {}

for header in headers:
    key, value = header.split(': ')
    dict_header[key] = value

In [ ]:
#Test
url = df['url'][0]
response = requests.get(url, headers=dict_header, proxies=proxies)
response

## Scrape listings

In [ ]:
def scrape_page(url, proxies=None):
    response = requests.get(url, headers=dict_header, proxies=proxies)
    response.raise_for_status()
    time.sleep(max(5.564878, 10.574878 + 2 * np.random.randn()))
    return response

def save_json(data, file_path):
    with open(file_path, 'w') as file:
        json.dump(data, file, indent=4)

def get_result_count(soup):
    result_count = soup.find_all('span', 'result-count')[0].text
    return int(result_count.replace(' results', '').replace(',', ''))

In [ ]:
def get_number_of_pages(result_count):
  number_of_pages = result_count//40
  if result_count%40 > 0:
    number_of_pages+=1
  return number_of_pages

In [ ]:
for index, row in df[217:218].iterrows():
    url = row['url']
    area_name = row['area_name'].replace('/', '-')

    try:
      response = scrape_page(url, proxies=proxies)
      soup = BeautifulSoup(response.text, 'html.parser')
      listings = soup.find_all('script')
      for listing in listings:
        try:
          json.loads(listing.text)
          if json.loads(listing.text)["props"]:
            data = json.loads(listing.text)
        except:
          continue

      full_file_path = f'{file_path}{area_name}.json'
      save_json(data, full_file_path)

      print(f'Done page 1: {area_name}')

      result_count = get_result_count(soup)
      number_of_pages = get_number_of_pages(result_count)

      if number_of_pages > 1:
        for page in range(2, number_of_pages + 1):
          try:
            pagination = f"pagination%22%3A%7B%22currentPage%22%3A{page}%7D%7D"
            new_url = url.split('pagination')[0] + pagination
            response = scrape_page(new_url, proxies=proxies)
            soup = BeautifulSoup(response.text, 'html.parser')
            listings = soup.find_all('script')
            for listing in listings:
              try:
                json.loads(listing.text)
                if json.loads(listing.text)["props"]:
                  data = json.loads(listing.text)
              except:
                continue
            full_file_path = f'{file_path}{area_name}_page{page}.json'
            save_json(data, full_file_path)
            result_count = get_result_count(soup)
            print(f'Done page {page}: {area_name}')
          except Exception as e:
            print(f'Error with {area_name} page {page}: {e}')

    except Exception as e:
        print(f'Error with {area_name}: {e}')

## Scrape the number of rentals listed

In [ ]:
for index, row in df[1:].iterrows():
    url = row['general_url']
    area_name = row['area_name']
    try:
      response = scrape_page(url, proxies=proxies)
      soup = BeautifulSoup(response.text, 'html.parser')
      result_count = get_result_count(soup)

      df.at[index, 'rentals_number'] = result_count
      df.to_csv(folder_path + 'df.csv', index=False)
      print(f'Done {area_name}')

    except Exception as e:
        print(f'Error with {area_name}: {e}')

Done Edison township, Middlesex County, New Jersey
Done Birmingham city, Alabama
Done Mobile city, Alabama
Done Montgomery city, Alabama
Done Tuscaloosa city, Alabama
Done Fayetteville city, Arkansas
Done Fort Smith city, Arkansas
Done Jonesboro city, Arkansas
Done Springdale city, Arkansas
Done Fort Collins city, Colorado
Done Lakewood city, Colorado
Done Hartford city, Connecticut
Done New Haven city, Connecticut
Done Stamford city, Connecticut
Done Waterbury city, Connecticut
Done Atlanta city, Georgia
Done Columbus city, Georgia
Done Savannah city, Georgia
Done Caldwell city, Idaho
Done Idaho Falls city, Idaho
Done Meridian city, Idaho
Done Nampa city, Idaho
Done Aurora city, Illinois
Done Joliet city, Illinois
Done Naperville city, Illinois
Done Rockford city, Illinois
Done Carmel city, Indiana
Done Evansville city, Indiana
Done South Bend city, Indiana
Done Cedar Rapids city, Iowa
Done Davenport city, Iowa
Done Iowa City city, Iowa
Done Sioux City city, Iowa
Done Kansas City city, Kansas
Done Olathe city, Kansas
Done Overland Park city, Kansas
Done Topeka city, Kansas
Done Bowling Green city, Kentucky
Done Baton Rouge city, Louisiana
Done Lafayette city, Louisiana
Done Lake Charles city, Louisiana
Done Shreveport city, Louisiana
Done Columbia CDP, Maryland
Done Germantown CDP, Maryland
Done Silver Spring CDP, Maryland
Done Waldorf CDP, Maryland
Done Cambridge city, Massachusetts
Done Lowell city, Massachusetts
Done Springfield city, Massachusetts
Done Worcester city, Massachusetts
Done Ann Arbor city, Michigan
Done Grand Rapids city, Michigan
Done Sterling Heights city, Michigan
Done Warren city, Michigan
Done Bloomington city, Minnesota
Done Duluth city, Minnesota
Done Rochester city, Minnesota
Done St. Paul city, Minnesota
Done Gulfport city, Mississippi
Done Columbia city, Missouri
Done Independence city, Missouri
Done St. Louis city, Missouri
Done Springfield city, Missouri
Done Missoula city, Montana
Done Paradise CDP, Nevada
Done Nashua city, New Hampshire
Done Elizabeth city, New Jersey
Done Paterson city, New Jersey
Done Las Cruces city, New Mexico
Done Rio Rancho city, New Mexico
Done Santa Fe city, New Mexico
Done Rochester city, New York
Done Syracuse city, New York
Done Yonkers city, New York
Done Bismarck city, North Dakota
Done Akron city, Ohio
Done Broken Arrow city, Oklahoma
Done Edmond city, Oklahoma
Done Norman city, Oklahoma
Done Eugene city, Oregon
Done Gresham city, Oregon
Done Hillsboro city, Oregon
Done Salem city, Oregon
Done Allentown city, Pennsylvania
Done Erie city, Pennsylvania
Done Reading city, Pennsylvania
Done Cranston city, Rhode Island
Done Pawtucket city, Rhode Island
Done Providence city, Rhode Island
Done Warwick city, Rhode Island
Done Charleston city, South Carolina
Done Columbia city, South Carolina
Done Mount Pleasant town, South Carolina
Done North Charleston city, South Carolina
Done Rock Hill city, South Carolina
Done Rapid City city, South Dakota
Done Sioux Falls city, South Dakota
Done Chattanooga city, Tennessee
Done Clarksville city, Tennessee
Done Knoxville city, Tennessee
Done Orem city, Utah
Done Provo city, Utah
Done Salt Lake City city, Utah
Done West Jordan city, Utah
Done West Valley City city, Utah
Done Arlington CDP, Virginia
Done Bellevue city, Washington
Done Tacoma city, Washington
Done Vancouver city, Washington
Done Green Bay city, Wisconsin
Done Kenosha city, Wisconsin
Done Racine city, Wisconsin
Done Cheyenne city, Wyoming
Done Honolulu County, Hawaii
Done Chesapeake city, Virginia
Done Norfolk city, Virginia
Done Huntsville city, Alabama
Done Anchorage municipality, Alaska
Done Chandler city, Arizona
Done Gilbert town, Arizona
Done Glendale city, Arizona
Done Mesa city, Arizona
Done Phoenix city, Arizona
Done Scottsdale city, Arizona
Done Tucson city, Arizona
Done Little Rock city, Arkansas
Done Anaheim city, California
Done Bakersfield city, California
Done Chula Vista city, California
Done Fresno city, California
Done Irvine city, California
Done Long Beach city, California
Done Los Angeles city, California
Done Oakland city, California
Done Riverside city, California
Done Sacramento city, California
Done San Bernardino city, California
Done San Diego city, California
Done San Francisco city, California
Done San Jose city, California
Done Santa Ana city, California
Done Stockton city, California
Done Aurora city, Colorado
Done Colorado Springs city, Colorado
Done Denver city, Colorado
Done Bridgeport city, Connecticut
Done Wilmington city, Delaware
Done Washington city, District of Columbia
Done Jacksonville city, Florida
Done Miami city, Florida
Done Orlando city, Florida
Done Port St. Lucie city, Florida
Done St. Petersburg city, Florida
Done Tampa city, Florida
Done Boise City city, Idaho
Done Chicago city, Illinois
Done Fort Wayne city, Indiana
Done Indianapolis city (balance), Indiana
Done Des Moines city, Iowa
Done Wichita city, Kansas
Done Lexington-Fayette urban county, Kentucky
Done Louisville/Jefferson County metro government (balance), Kentucky
Done New Orleans city, Louisiana
Done Portland city, Maine
Done Baltimore city, Maryland
Done Boston city, Massachusetts
Done Detroit city, Michigan
Done Minneapolis city, Minnesota
Done Jackson city, Mississippi
Done Kansas City city, Missouri
Done Billings city, Montana
Done Lincoln city, Nebraska
Done Omaha city, Nebraska
Done Henderson city, Nevada
Done Las Vegas city, Nevada
Done North Las Vegas city, Nevada
Done Reno city, Nevada
Done Manchester city, New Hampshire
Done Jersey City city, New Jersey
Done Newark city, New Jersey
Done Albuquerque city, New Mexico
Done Buffalo city, New York
Done New York city, New York
Done Charlotte city, North Carolina
Done Durham city, North Carolina
Done Greensboro city, North Carolina
Done Raleigh city, North Carolina
Done Winston-Salem city, North Carolina
Done Fargo city, North Dakota
Done Cincinnati city, Ohio
Done Cleveland city, Ohio
Done Columbus city, Ohio
Done Toledo city, Ohio
Done Oklahoma City city, Oklahoma
Done Tulsa city, Oklahoma
Done Portland city, Oregon
Done Philadelphia city, Pennsylvania
Done Pittsburgh city, Pennsylvania
Done Memphis city, Tennessee
Done Nashville-Davidson metropolitan government (balance), Tennessee
Done Arlington city, Texas
Done Austin city, Texas
Done Corpus Christi city, Texas
Done Dallas city, Texas
Done El Paso city, Texas
Done Fort Worth city, Texas
Done Frisco city, Texas
Done Garland city, Texas
Done Houston city, Texas
Done Irving city, Texas
Done Laredo city, Texas
Done Lubbock city, Texas
Done Plano city, Texas
Done San Antonio city, Texas
Done Richmond city, Virginia
Done Virginia Beach city, Virginia
Done Seattle city, Washington
Done Spokane city, Washington
Done Madison city, Wisconsin
Done Milwaukee city, Wisconsin
Done Laramie County, Wyoming

# Read scraped data

In [ ]:
json_files = [f for f in os.listdir(file_path) if f.endswith('.json')]

In [ ]:
data = []

In [ ]:
for file in json_files:
    with open(os.path.join(file_path, file), 'r') as json_file:
      try:
        json_data = json.load(json_file)
        json_data = json_data['props']['pageProps']['searchPageState']['cat1']['searchResults']['listResults']
        file_name = file.split('.json')[0].split('_')[0]

        for item in json_data:
          id = item.get('id', None)
          price = item.get('unformattedPrice', None)
          size = item.get('area', None)

          data.append({'area_name': file_name, 'id': id, 'price': price,
                       'size': size})

      except Exception as e:
        print(f'Error with {file}: {e}')

In [ ]:
properties = pd.DataFrame(data)

In [ ]:
properties.drop_duplicates(subset=['id'], inplace=True)

In [ ]:
#properties.to_excel('scraped_properties.xlsx', index=False)

In [ ]:
properties = pd.read_excel(folder_path + 'scraped_properties.xlsx')

In [ ]:
properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54327 entries, 0 to 54326
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   area_name  54327 non-null  object
 1   id         54327 non-null  object
 2   price      38517 non-null  float64
 3   size       31099 non-null  float64
dtypes: float64(2), object(2)
memory usage: 1.7+ MB

In [ ]:
wrong_ids_count = properties['id'].str.contains(r'\d+\.\d+--\d+\.\d+').sum()

In [ ]:
wrong_ids_count

15809

In [ ]:
properties

                    area_name                   id   price   size
0            Akron city, Ohio   41.012787--81.5305     NaN    NaN
1            Akron city, Ohio           2066754779   690.0  650.0
2            Akron city, Ohio  41.09719--81.546364     NaN    NaN
3            Akron city, Ohio   40.98566--81.48832     NaN    NaN
4            Akron city, Ohio           2099146109   829.0  600.0
...                       ...                  ...     ...    ...
54322  Yonkers city, New York           2060666632  1425.0  670.0
54323  Yonkers city, New York           2052913657  1200.0    NaN
54324  Yonkers city, New York           2079536917  1450.0  625.0
54325  Yonkers city, New York           2053184488  1450.0  600.0
54326  Yonkers city, New York           2056438644  1434.0  574.0

[54327 rows x 4 columns]

In [ ]:
len(properties.area_name.unique())

217

In [ ]:
aggregated_data = properties.groupby('area_name').agg(
    properties_count=('id', 'count'),
    average_size=('size', 'mean')
).reset_index()

In [ ]:
aggregated_data.columns = ['area_name', 'rentals_30_%', 'Average Property Size']

In [ ]:
aggregated_data

                              area_name  rentals_30_%  Average Property Size
0                      Akron city, Ohio           334             995.407407
1          Albuquerque city, New Mexico           340             692.387755
2          Allentown city, Pennsylvania            92             730.718750
3              Anaheim city, California             5             675.000000
4        Anchorage municipality, Alaska           122             826.517857
..                                  ...           ...                    ...
212                Wichita city, Kansas           307            1261.239496
213           Wilmington city, Delaware           100             848.119403
214  Winston-Salem city, North Carolina           206             829.609091
215       Worcester city, Massachusetts            31             690.846154
216              Yonkers city, New York             9             628.166667

[217 rows x 3 columns]

In [ ]:
df = df.merge(aggregated_data, on='area_name', how='left')

In [ ]:
df['% Of Rentals That Can Be Afforded'] = df['rentals_30_%']/df['rentals_number']

In [ ]:
df['rentals_30_%'] = df['rentals_30_%'].fillna(0)

In [ ]:
df['% Of Rentals That Can Be Afforded'] = df['% Of Rentals That Can Be Afforded'].fillna(0)

In [ ]:
df['Average Property Size'] = df['Average Property Size'].fillna(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 222 entries, 0 to 221
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   median_earnings                    222 non-null    int64
 1   area_name                          222 non-null    object
 2   city                               222 non-null    object
 3   state                              222 non-null    object
 4   30% of monthly salary              222 non-null    float64
 5   url                                222 non-null    object
 6   general_url                        222 non-null    object
 7   rentals_number                     222 non-null    float64
 8   rentals_30_%                       222 non-null    float64
 9   Average Property Size              222 non-null    float64
 10  % Of Rentals That Can Be Afforded  222 non-null    float64
dtypes: float64(5), int64(1), object(5)
memory usage: 20.8+ KB

In [ ]:
df

,median_earnings,area_name,city,state,30% of monthly salary,url,general_url,rentals_number,rentals_30_%,Average Property Size,% Of Rentals That Can Be Afforded
0,51320,"Grand Forks County, North Dakota",Grand Forks,North Dakota,1283.000,https://www.zillow.com/grand-forks-nd/rentals/...,https://www.zillow.com/grand-forks-nd/rentals/,104.0,74.0,733.750000,0.711538
1,80096,"Edison township, Middlesex County, New Jersey",Edison,New Jersey,2002.400,https://www.zillow.com/edison-nj/rentals/?sear...,https://www.zillow.com/edison-nj/rentals/,82.0,25.0,733.133333,0.304878
2,48837,"Birmingham city, Alabama",Birmingham,Alabama,1220.925,https://www.zillow.com/birmingham-al/rentals/?...,https://www.zillow.com/birmingham-al/rentals/,775.0,479.0,1006.850746,0.618065
3,51468,"Mobile city, Alabama",Mobile,Alabama,1286.700,https://www.zillow.com/mobile-al/rentals/?sear...,https://www.zillow.com/mobile-al/rentals/,264.0,119.0,1029.463768,0.450758
4,47376,"Montgomery city, Alabama",Montgomery,Alabama,1184.400,https://www.zillow.com/montgomery-al/rentals/?...,https://www.zillow.com/montgomery-al/rentals/,463.0,240.0,1159.223464,0.518359
...,...,...,...,...,...,...,...,...,...,...,...
217,90159,"Seattle city, Washington",Seattle,Washington,2253.975,https://www.zillow.com/seattle-wa/rentals/?sea...,https://www.zillow.com/seattle-wa/rentals/,2748.0,984.0,610.455013,0.358079
218,60547,"Spokane city, Washington",Spokane,Washington,1513.675,https://www.zillow.com/spokane-wa/rentals/?sea...,https://www.zillow.com/spokane-wa/rentals/,517.0,316.0,826.673171,0.611219
219,65242,"Madison city, Wisconsin",Madison,Wisconsin,1631.050,https://www.zillow.com/madison-wi/rentals/?sea...,https://www.zillow.com/madison-wi/rentals/,474.0,274.0,703.149660,0.578059
220,54654,"Milwaukee city, Wisconsin",Milwaukee,Wisconsin,1366.350,https://www.zillow.com/milwaukee-wi/rentals/?s...,https://www.zillow.com/milwaukee-wi/rentals/,1011.0,614.0,973.806452,0.607319
221,58526,"Laramie County, Wyoming",Laramie,Wyoming,1463.150,https://www.zillow.com/laramie-wy/rentals/?sea...,https://www.zillow.com/laramie-wy/rentals/,55.0,35.0,840.285714,0.636364

# Organise tabs and rankings

## Rent High

Rent High: Showing the 20 US cities with the highest percentage of properties available to rent for 30% of the local average salary

Columns: State, city, % Of Rentals That Can Be Afforded

In [ ]:
rent_high = df.sort_values(by='% Of Rentals That Can Be Afforded', ascending=False).head(20)
rent_high.drop(columns=['area_name', 'url', 'general_url', 'Average Property Size',
                        'median_earnings', '30% of monthly salary'], inplace=True)
rent_high

,city,state,rentals_number,rentals_30_%,% Of Rentals That Can Be Afforded
42,Shreveport,Louisiana,315.0,269.0,0.853968
37,Topeka,Kansas,240.0,201.0,0.837500
15,Waterbury,Connecticut,157.0,131.0,0.834395
193,Toledo,Ohio,475.0,390.0,0.821053
76,Akron,Ohio,430.0,334.0,0.776744
112,Racine,Wisconsin,84.0,64.0,0.761905
31,Davenport,Iowa,129.0,98.0,0.759690
61,Independence,Missouri,187.0,140.0,0.748663
17,Columbus,Georgia,349.0,261.0,0.747851
159,Des Moines,Iowa,281.0,209.0,0.743772
28,Evansville,Indiana,148.0,110.0,0.743243
111,Kenosha,Wisconsin,64.0,47.0,0.734375
189,Fargo,North Dakota,275.0,199.0,0.723636
30,Cedar Rapids,Iowa,247.0,177.0,0.716599
41,Lake Charles,Louisiana,288.0,205.0,0.711806
0,Grand Forks,North Dakota,104.0,74.0,0.711538
190,Cincinnati,Ohio,1164.0,827.0,0.710481
33,Sioux City,Iowa,48.0,34.0,0.708333
97,Sioux Falls,South Dakota,315.0,217.0,0.688889
62,St. Louis,Missouri,1180.0,810.0,0.686441

## Rent Low

Rent Low:  Showing the 20 US cities with the lowest percentage of properties available to rent for 30% of the local average salary

Columns: State, city, % Of Rentals That Can Be Afforded

In [ ]:
rent_low = df.sort_values(by='% Of Rentals That Can Be Afforded', ascending=True).head(26)
rent_low.drop(columns=['area_name', 'url', 'general_url', 'Average Property Size',
                        'median_earnings', '30% of monthly salary'], inplace=True)
rent_low

,city,state,rentals_number,rentals_30_%,% Of Rentals That Can Be Afforded
67,Elizabeth,New Jersey,128.0,0.0,0.000000
68,Paterson,New Jersey,141.0,0.0,0.000000
131,Irvine,California,569.0,0.0,0.000000
71,Santa Fe,New Mexico,210.0,0.0,0.000000
161,Lexington-Fayette,Kentucky,2.0,0.0,0.000000
162,Louisville/Jefferson,Kentucky,37.0,0.0,0.000000
47,Cambridge,Massachusetts,1035.0,3.0,0.002899
152,Port St. Lucie,Florida,388.0,3.0,0.007732
141,Santa Ana,California,128.0,1.0,0.007812
127,Anaheim,California,317.0,5.0,0.015773
65,Paradise,Nevada,364.0,6.0,0.016484
74,Yonkers,New York,410.0,9.0,0.021951
164,Portland,Maine,134.0,3.0,0.022388
34,Kansas City,Kansas,1277.0,36.0,0.028191
146,Bridgeport,Connecticut,222.0,7.0,0.031532
129,Chula Vista,California,221.0,7.0,0.031674
180,Newark,New Jersey,620.0,21.0,0.033871
89,Providence,Rhode Island,501.0,20.0,0.039920
150,Miami,Florida,2628.0,106.0,0.040335
166,Boston,Massachusetts,7933.0,363.0,0.045758
183,New York,New York,9768.0,541.0,0.055385
138,San Diego,California,3418.0,270.0,0.078994
135,Riverside,California,383.0,31.0,0.080940
133,Los Angeles,California,11666.0,978.0,0.083833
151,Orlando,Florida,1787.0,154.0,0.086178
90,Warwick,Rhode Island,34.0,3.0,0.088235

## Sq Ft High

Sq Ft High: Showing the 20 US cities with the highest average square foot rental that can be rented with 30% of the local average salary
Columns: State, city, Average Size (Sq Ft) Of Rental

In [ ]:
sq_ft_high = df.sort_values(by='Average Property Size', ascending=False).head(20)
sq_ft_high.drop(columns=['area_name', 'url', 'general_url', '% Of Rentals That Can Be Afforded',
                        'median_earnings', '30% of monthly salary', 'rentals_number'], inplace=True)
sq_ft_high

             city          state  rentals_30_%  Average Property Size
166        Boston  Massachusetts         363.0            4480.224806
150         Miami        Florida         106.0            2342.281690
207        Frisco          Texas          68.0            1508.880000
27         Carmel        Indiana          43.0            1291.035714
101          Orem           Utah          36.0            1283.909091
160       Wichita         Kansas         307.0            1261.239496
78         Edmond       Oklahoma         128.0            1259.391304
179   Jersey City     New Jersey         328.0            1227.409091
4      Montgomery        Alabama         240.0            1159.223464
42     Shreveport      Louisiana         269.0            1130.401042
25     Naperville       Illinois          38.0            1127.705882
77   Broken Arrow       Oklahoma          19.0            1114.857143
28     Evansville        Indiana         110.0            1113.819672
15      Waterbury    Connecticut         131.0            1089.911392
191     Cleveland           Ohio         790.0            1084.018405
169       Jackson    Mississippi         131.0            1064.387755
175     Las Vegas         Nevada         794.0            1063.478528
212       Lubbock          Texas         585.0            1062.977597
199       Memphis      Tennessee         907.0            1060.571207
17       Columbus        Georgia         261.0            1059.193396

## Sq Ft Low

Sq Ft Low: Showing the 20 US cities with the lowest average square foot rental that can be rented with 30% of the local average salary
Columns: State, city, Average Size (Sq Ft) Of Rental

In [ ]:
sq_ft_low = df.sort_values(by='Average Property Size', ascending=True).head(27)
sq_ft_low.drop(columns=['area_name', 'url', 'general_url', '% Of Rentals That Can Be Afforded',
                        'median_earnings', '30% of monthly salary', 'rentals_number'], inplace=True)
sq_ft_low

                     city          state  rentals_30_%  Average Property Size
141             Santa Ana     California           1.0               0.000000
67              Elizabeth     New Jersey           0.0               0.000000
68               Paterson     New Jersey           0.0               0.000000
71               Santa Fe     New Mexico           0.0               0.000000
162  Louisville/Jefferson       Kentucky           0.0               0.000000
161     Lexington-Fayette       Kentucky           0.0               0.000000
131                Irvine     California           0.0               0.000000
152        Port St. Lucie        Florida           3.0             325.000000
47              Cambridge  Massachusetts           3.0             337.500000
114              Honolulu         Hawaii          85.0             390.479167
180                Newark     New Jersey          21.0             401.666667
138             San Diego     California         270.0             440.316092
129           Chula Vista     California           7.0             464.285714
133           Los Angeles     California         978.0             486.814953
89             Providence   Rhode Island          20.0             497.454545
90                Warwick   Rhode Island           3.0             500.000000
164              Portland          Maine           3.0             507.500000
132            Long Beach     California         308.0             508.314465
80                 Eugene         Oregon          75.0             514.307692
135             Riverside     California          31.0             521.181818
49            Springfield  Massachusetts          10.0             529.000000
64               Missoula        Montana          41.0             554.206897
153        St. Petersburg        Florida         131.0             555.549020
139         San Francisco     California         915.0             555.987288
137        San Bernardino     California          30.0             556.550000
51              Ann Arbor       Michigan          58.0             566.391304
96             Rapid City   South Dakota          35.0             581.095238

# Create an Excel file

In [ ]:
# Create an Excel writer object

writer = pd.ExcelWriter('What Can You Rent in U.S. Cities with the Median Graduate Salary?.xlsx')

In [ ]:
rent_high.to_excel(writer, sheet_name='Rent high', index=False)
rent_low.to_excel(writer, sheet_name='Rent low', index=False)
sq_ft_high.to_excel(writer, sheet_name='Sq Ft high', index=False)
sq_ft_low.to_excel(writer, sheet_name='Sq Ft low', index=False)
df.to_excel(writer, sheet_name='Raw Data', index=False)

In [ ]:
# Save the Excel file
writer.save()

<ipython-input-30-a6322a9d98fd>:2: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()