In [100]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import time
import os

# Calculate the how much men and women would need to save for a comfortable retirement in each state, then calculate the difference

## Take the average retirement age of 64.

In [2]:
avg_retirement = 64

## Take the most recent life expectancies for each gender in each state

https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_life_expectancy

In [3]:
tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_life_expectancy')

In [5]:
life_expectancies = tables[0]

In [8]:
new_columns = ['state', 'overall_2019', 'males_2019', 'females_2019', 'F Δ M 2019', 
               '2019→2020', 'overall_2020', 'males_2020', 'females_2020', 'F Δ M 2020']

In [9]:
life_expectancies.columns = new_columns

In [11]:
life_expectancies.drop(columns=['overall_2019', 'males_2019', 'females_2019', 
                                'F Δ M 2019', '2019→2020',], inplace=True)

In [12]:
life_expectancies

                 state  overall_2020  males_2020  females_2020  F Δ M 2020
0        US on average          77.0        76.2          79.9         3.7
1           California          79.0        76.2          82.0         5.8
2               Hawaii          80.7        77.6          83.8         6.2
3             New York          77.7        74.8          80.7         5.9
4            Minnesota          79.1        76.8          81.4         4.6
5        Massachusetts          79.0        76.4          81.5         5.1
6          Connecticut          78.4        75.6          81.3         5.7
7           New Jersey          77.5        74.6          80.5         5.9
8   Washington (state)          79.2        76.9          81.6         4.7
9             Colorado          78.3        75.8          80.9         5.1
10             Vermont          78.8        76.1          81.4         5.3
11                Utah          78.6        76.7          80.6         3.9
12              Oregon          78.8        76.3          81.3         5.0
13               Idaho          78.4        76.1          80.8         4.7
14        Rhode Island          78.2        75.5          80.9         5.4
15       New Hampshire          79.0        76.5          81.5         5.0
16           Wisconsin          77.7        75.2          80.3         5.1
17            Nebraska          77.7        75.2          80.3         5.1
18            Virginia          77.6        75.1          80.1         5.0
19                Iowa          77.5        74.9          80.1         5.2
20            Illinois          76.8        73.8          79.8         6.0
21             Florida          77.5        74.6          80.5         5.9
22        North Dakota          76.9        74.2          80.0         5.8
23             Arizona          76.3        73.4          79.5         6.1
24               Texas          76.5        73.7          79.3         5.6
25            Maryland          76.8        73.8          79.7         5.9
26             Montana          76.8        74.2          79.6         5.4
27        South Dakota          76.7        74.2          79.4         5.2
28               Maine          77.8        74.9          80.7         5.8
29        Pennsylvania          76.8        74.0          79.6         5.6
30              Kansas          76.4        73.8          79.2         5.4
31            Delaware          76.7        73.9          79.5         5.6
32              Nevada          76.3        73.5          79.2         5.7
33            Michigan          76.0        73.4          78.8         5.4
34    Washington, D.C.          75.3        71.7          78.7         7.0
35              Alaska          76.6        74.3          79.2         4.9
36             Wyoming          76.3        74.0          78.9         4.9
37      North Carolina          76.1        73.3          79.0         5.7
38             Georgia          75.6        72.8          78.3         5.5
39             Indiana          75.0        72.3          77.9         5.6
40                Ohio          75.3        72.5          78.1         5.6
41            Missouri          75.1        72.1          78.1         6.0
42          New Mexico          74.5        71.3          77.8         6.5
43      South Carolina          74.8        71.7          78.0         6.3
44            Oklahoma          74.1        71.5          76.9         5.4
45            Arkansas          73.8        71.1          76.6         5.5
46           Louisiana          73.1        69.9          76.4         6.5
47           Tennessee          73.8        70.7          77.0         6.3
48            Kentucky          73.5        70.6          76.5         5.9
49             Alabama          73.2        70.1          76.4         6.3
50       West Virginia          72.8        69.8          76.1         6.3
51         Mississippi          71.9        68.6          75.2         6.6

## Take the cost of living in each state from MIT Source

https://livingwage.mit.edu/states/48

In [48]:
living_cost = pd.DataFrame()

In [14]:
urls = []

In [17]:
for i in range(1,52):
    url = f'https://livingwage.mit.edu/states/{i}'
    urls.append(url)

In [18]:
urls

['https://livingwage.mit.edu/states/1',
 'https://livingwage.mit.edu/states/2',
 'https://livingwage.mit.edu/states/3',
 'https://livingwage.mit.edu/states/4',
 'https://livingwage.mit.edu/states/5',
 'https://livingwage.mit.edu/states/6',
 'https://livingwage.mit.edu/states/7',
 'https://livingwage.mit.edu/states/8',
 'https://livingwage.mit.edu/states/9',
 'https://livingwage.mit.edu/states/10',
 'https://livingwage.mit.edu/states/11',
 'https://livingwage.mit.edu/states/12',
 'https://livingwage.mit.edu/states/13',
 'https://livingwage.mit.edu/states/14',
 'https://livingwage.mit.edu/states/15',
 'https://livingwage.mit.edu/states/16',
 'https://livingwage.mit.edu/states/17',
 'https://livingwage.mit.edu/states/18',
 'https://livingwage.mit.edu/states/19',
 'https://livingwage.mit.edu/states/20',
 'https://livingwage.mit.edu/states/21',
 'https://livingwage.mit.edu/states/22',
 'https://livingwage.mit.edu/states/23',
 'https://livingwage.mit.edu/states/24',
 'https://livingwage.mit.edu/states/25',
 'https://livingwage.mit.edu/states/26',
 'https://livingwage.mit.edu/states/27',
 'https://livingwage.mit.edu/states/28',
 'https://livingwage.mit.edu/states/29',
 'https://livingwage.mit.edu/states/30',
 'https://livingwage.mit.edu/states/31',
 'https://livingwage.mit.edu/states/32',
 'https://livingwage.mit.edu/states/33',
 'https://livingwage.mit.edu/states/34',
 'https://livingwage.mit.edu/states/35',
 'https://livingwage.mit.edu/states/36',
 'https://livingwage.mit.edu/states/37',
 'https://livingwage.mit.edu/states/38',
 'https://livingwage.mit.edu/states/39',
 'https://livingwage.mit.edu/states/40',
 'https://livingwage.mit.edu/states/41',
 'https://livingwage.mit.edu/states/42',
 'https://livingwage.mit.edu/states/43',
 'https://livingwage.mit.edu/states/44',
 'https://livingwage.mit.edu/states/45',
 'https://livingwage.mit.edu/states/46',
 'https://livingwage.mit.edu/states/47',
 'https://livingwage.mit.edu/states/48',
 'https://livingwage.mit.edu/states/49',
 'https://livingwage.mit.edu/states/50',
 'https://livingwage.mit.edu/states/51']

In [52]:
for url in urls[2:]:
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text)

        state = soup.find_all('h1')[-1].text.split(' ')[-1]
        
        tables = soup.find_all('table')
        second_table = tables[1]
        rows = second_table.find_all('tr')
        
        data = []
        for row in rows:
            cols = row.find_all('td')
            cols = [col.text.strip() for col in cols]
            data.append(cols)
            
        data = pd.DataFrame(data)
        data = data[[0, 1]]
        data['state'] = state
        
        living_cost = pd.concat([living_cost, data])
        print('Done', state)
        time.sleep(5)
    except Exception as e:
            print(f'Exception: {e}')

Exception: 404 Client Error: Not Found for url: https://livingwage.mit.edu/states/3
Done Arizona
Done Arkansas
Done California
Exception: 404 Client Error: Not Found for url: https://livingwage.mit.edu/states/7
Done Colorado
Done Connecticut
Done Delaware
Done Columbia
Done Florida
Done Georgia
Exception: 404 Client Error: Not Found for url: https://livingwage.mit.edu/states/14
Done Hawaii
Done Idaho
Done Illinois
Done Indiana
Done Iowa
Done Kansas
Done Kentucky
Done Louisiana
Done Maine
Done Maryland
Done Massachusetts
Done Michigan
Done Minnesota
Done Mississippi
Done Missouri
Done Montana
Done Nebraska
Done Nevada
Done Hampshire
Done Jersey
Done Mexico
Done York
Done Carolina
Done Dakota
Done Ohio
Done Oklahoma
Done Oregon
Done Pennsylvania
Exception: 404 Client Error: Not Found for url: https://livingwage.mit.edu/states/43
Done Island
Done Carolina
Done Dakota
Done Tennessee
Done Texas
Done Utah
Done Vermont
Done Virginia

In [54]:
living_cost.columns = ['expense', '$', 'state']

In [56]:
living_cost = living_cost[living_cost['expense'] == 'Required annual income before taxes']

In [58]:
living_cost = living_cost[['$', 'state']]

In [59]:
living_cost.columns = ['Required annual income before taxes', 'state']

In [61]:
living_cost = living_cost[['state', 'Required annual income before taxes']]

In [66]:
new_rows_df = pd.DataFrame({
    'state': ['Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
    'Required annual income before taxes': ['$53,242', '$39,386', '$42,062', '$43,823']
})

In [67]:
living_cost = pd.concat([living_cost, new_rows_df], ignore_index=True)

In [69]:
#living_cost.to_csv('living_cost.csv', index=False)

In [133]:
living_cost = pd.read_csv('living_cost_new.csv')

In [136]:
living_cost

                 state  Required annual income before taxes
0              Alabama                                41911
1               Alaska                                48375
2              Arizona                                48677
3             Arkansas                                39724
4           California                                56825
5             Colorado                                51644
6          Connecticut                                50194
7             Delaware                                47064
8             Columbia                                49714
9              Florida                                46645
10             Georgia                                48448
11              Hawaii                                56841
12               Idaho                                44366
13            Illinois                                47559
14             Indiana                                42510
15                Iowa                                41678
16              Kansas                                42337
17            Kentucky                                40355
18           Louisiana                                41233
19               Maine                                45844
20            Maryland                                51460
21       Massachusetts                                58009
22            Michigan                                42187
23           Minnesota                                44626
24         Mississippi                                41361
25            Missouri                                42024
26             Montana                                42374
27            Nebraska                                41849
28              Nevada                                46727
29       New Hampshire                                49045
30          New Jersey                                51504
31          New Mexico                                41807
32            New York                                55878
33      North Carolina                                44848
34        North Dakota                                40262
35                Ohio                                40359
36            Oklahoma                                40211
37              Oregon                                50553
38        Pennsylvania                                45661
39        Rhode Island                                50418
40      South Carolina                                44152
41        South Dakota                                40718
42           Tennessee                                43196
43               Texas                                43508
44                Utah                                46850
45             Vermont                                47892
46            Virginia                                49973
47  Washington (state)                                53242
48       West Virginia                                39386
49           Wisconsin                                42062
50             Wyoming                                43823

## Multiply this annual figure for each state by 20% = more comfortable retirement

In [135]:
living_cost['Required annual income before taxes'] = living_cost['Required annual income before taxes'].apply(lambda x: int(x.replace('$', '').replace(',', '')))

In [86]:
living_cost['Required annual income before taxes'] = living_cost['Required annual income before taxes'].apply(lambda x: x*1.2)

In [87]:
living_cost

                 state  Required annual income before taxes
0              Alabama                              50293.2
1               Alaska                              58050.0
2              Arizona                              58412.4
3             Arkansas                              47668.8
4           California                              68190.0
5             Colorado                              61972.8
6          Connecticut                              60232.8
7             Delaware                              56476.8
8             Columbia                              59656.8
9              Florida                              55974.0
10             Georgia                              58137.6
11              Hawaii                              68209.2
12               Idaho                              53239.2
13            Illinois                              57070.8
14             Indiana                              51012.0
15                Iowa                              50013.6
16              Kansas                              50804.4
17            Kentucky                              48426.0
18           Louisiana                              49479.6
19               Maine                              55012.8
20            Maryland                              61752.0
21       Massachusetts                              69610.8
22            Michigan                              50624.4
23           Minnesota                              53551.2
24         Mississippi                              49633.2
25            Missouri                              50428.8
26             Montana                              50848.8
27            Nebraska                              50218.8
28              Nevada                              56072.4
29       New Hampshire                              58854.0
30          New Jersey                              61804.8
31          New Mexico                              50168.4
32            New York                              67053.6
33      North Carolina                              53817.6
34        North Dakota                              48314.4
35                Ohio                              48430.8
36            Oklahoma                              48253.2
37              Oregon                              60663.6
38        Pennsylvania                              54793.2
39        Rhode Island                              60501.6
40      South Carolina                              52982.4
41        South Dakota                              48861.6
42           Tennessee                              51835.2
43               Texas                              52209.6
44                Utah                              56220.0
45             Vermont                              57470.4
46            Virginia                              59967.6
47  Washington (state)                              63890.4
48       West Virginia                              47263.2
49           Wisconsin                              50474.4
50             Wyoming                              52587.6

## Calculate the difference in years between the retirement age and life expectancy for each gender in each state.

In [76]:
life_expectancies = life_expectancies[['state', 'males_2020', 'females_2020']]

In [78]:
life_expectancies['Years_After_Retirement_Male'] = life_expectancies['males_2020'].apply(lambda x: x - avg_retirement)

/Users/anna.zemit/opt/anaconda3/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [80]:
life_expectancies['Years_After_Retirement_Female'] = life_expectancies['females_2020'].apply(lambda x: x - avg_retirement)

In [81]:
life_expectancies

,state,males_2020,females_2020,Years_After_Retirement_Male,Years_After_Retirement_Female
0,US on average,76.2,79.9,12.2,15.9
1,California,76.2,82.0,12.2,18.0
2,Hawaii,77.6,83.8,13.6,19.8
3,New York,74.8,80.7,10.8,16.7
4,Minnesota,76.8,81.4,12.8,17.4
5,Massachusetts,76.4,81.5,12.4,17.5
6,Connecticut,75.6,81.3,11.6,17.3
7,New Jersey,74.6,80.5,10.6,16.5
8,Washington (state),76.9,81.6,12.9,17.6
9,Colorado,75.8,80.9,11.8,16.9
10,Vermont,76.1,81.4,12.1,17.4
11,Utah,76.7,80.6,12.7,16.6
12,Oregon,76.3,81.3,12.3,17.3
13,Idaho,76.1,80.8,12.1,16.8
14,Rhode Island,75.5,80.9,11.5,16.9
15,New Hampshire,76.5,81.5,12.5,17.5
16,Wisconsin,75.2,80.3,11.2,16.3
17,Nebraska,75.2,80.3,11.2,16.3
18,Virginia,75.1,80.1,11.1,16.1
19,Iowa,74.9,80.1,10.9,16.1
20,Illinois,73.8,79.8,9.8,15.8
21,Florida,74.6,80.5,10.6,16.5
22,North Dakota,74.2,80.0,10.2,16.0
23,Arizona,73.4,79.5,9.4,15.5
24,Texas,73.7,79.3,9.7,15.3
25,Maryland,73.8,79.7,9.8,15.7
26,Montana,74.2,79.6,10.2,15.6
27,South Dakota,74.2,79.4,10.2,15.4
28,Maine,74.9,80.7,10.9,16.7
29,Pennsylvania,74.0,79.6,10.0,15.6
30,Kansas,73.8,79.2,9.8,15.2
31,Delaware,73.9,79.5,9.9,15.5
32,Nevada,73.5,79.2,9.5,15.2
33,Michigan,73.4,78.8,9.4,14.8
34,"Washington, D.C.",71.7,78.7,7.7,14.7
35,Alaska,74.3,79.2,10.3,15.2
36,Wyoming,74.0,78.9,10.0,14.9
37,North Carolina,73.3,79.0,9.3,15.0
38,Georgia,72.8,78.3,8.8,14.3
39,Indiana,72.3,77.9,8.3,13.9
40,Ohio,72.5,78.1,8.5,14.1
41,Missouri,72.1,78.1,8.1,14.1
42,New Mexico,71.3,77.8,7.3,13.8
43,South Carolina,71.7,78.0,7.7,14.0
44,Oklahoma,71.5,76.9,7.5,12.9
45,Arkansas,71.1,76.6,7.1,12.6
46,Louisiana,69.9,76.4,5.9,12.4
47,Tennessee,70.7,77.0,6.7,13.0
48,Kentucky,70.6,76.5,6.6,12.5
49,Alabama,70.1,76.4,6.1,12.4
50,West Virginia,69.8,76.1,5.8,12.1
51,Mississippi,68.6,75.2,4.6,11.2

## Calculate the savings needed to retire for both genders in each state

In [92]:
life_expectancies = life_expectancies.merge(living_cost, on=['state'], how='left').dropna(subset = ['Required annual income before taxes'])

In [94]:
life_expectancies['Savings_Male'] = life_expectancies['Years_After_Retirement_Male'] * life_expectancies['Required annual income before taxes']

In [96]:
life_expectancies['Savings_Female'] = life_expectancies['Years_After_Retirement_Female'] * life_expectancies['Required annual income before taxes']

In [97]:
life_expectancies

,state,males_2020,females_2020,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes,Savings_Male,Savings_Female
1,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00
2,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16
3,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12
4,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88
5,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00
6,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44
7,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20
8,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04
9,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32
10,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96
11,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00
12,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28
13,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56
14,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04
15,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00
16,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72
17,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44
18,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36
19,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96
20,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64
21,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00
22,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40
23,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20
24,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88
25,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40
26,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28
27,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64
28,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76
29,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92
30,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88
31,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40
32,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48
33,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12
35,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00
36,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24
37,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00
38,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68
39,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80
40,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28
41,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08
42,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92
43,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60
44,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28
45,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88
46,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04
47,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60
48,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00
49,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68
50,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72
51,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84

## Calculate how much more women would need to save in each state.

In [98]:
life_expectancies['Extra_Savings_for_Women'] = life_expectancies['Savings_Female'] - life_expectancies['Savings_Male']

In [152]:
life_expectancies.columns = ['state', 'males_2020', 'females_2020', 'Years_After_Retirement_Male',
       'Years_After_Retirement_Female', 'Required annual income before taxes * 20%',
       'Savings_Male', 'Savings_Female', 'Extra_Savings_for_Women']

In [153]:
life_expectancies

,state,males_2020,females_2020,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes * 20%,Savings_Male,Savings_Female,Extra_Savings_for_Women
1,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00,395502.00
2,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16,422897.04
3,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12,395616.24
4,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88,246335.52
5,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00,355015.08
6,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44,343326.96
7,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20,364648.32
8,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04,300284.88
9,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32,316061.28
10,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96,304593.12
11,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00,219258.00
12,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28,303318.00
13,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56,250224.24
14,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04,326708.64
15,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00,294270.00
16,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72,257419.44
17,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44,256115.88
18,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36,299838.00
19,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96,260070.72
20,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64,342424.80
21,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00,330246.60
22,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40,280223.52
23,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20,356315.64
24,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88,292373.76
25,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40,364336.80
26,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28,274583.52
27,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64,254080.32
28,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76,319074.24
29,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92,306841.92
30,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88,274343.76
31,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40,316270.08
32,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48,319612.68
33,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12,273371.76
35,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00,284445.00
36,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24,257679.24
37,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00,306760.32
38,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68,319756.80
39,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80,285667.20
40,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28,271212.48
41,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08,302572.80
42,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92,326094.60
43,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60,333789.12
44,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28,260567.28
45,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88,262178.40
46,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04,321617.40
47,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60,326561.76
48,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00,285713.40
49,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68,316847.16
50,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72,297758.16
51,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84,327579.12

# Calculate the years men and women would need to work to save for a comfortable retirement in each state, then calculate the difference

## Pull the median earnings for men and women in each state

https://data.census.gov/table/ACSST1Y2022.S2412?q=s2412&moe=false

In [101]:
folder_path = '/Users/anna.zemit/Desktop/Programming/2024/24. How Much More Do Women Need to Save For A Comfortable Retirement?/median earnings'

In [119]:
# List to store individual DataFrames
dfs = []

In [120]:
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        file_path = os.path.join(folder_path, filename)
        
        # Read the CSV file into a DataFrame
        df = pd.read_csv(file_path)
        
        # Extract the state name from the header row (assumed to be in the first row or specific header)
        state_name = df.columns[1].split('!!')[0].strip()  # Modify the splitting method if the state name format is different
        
        # Standardize column names by removing state name and keeping only the column description
        df.columns = [col.split('!!')[-1].strip() for col in df.columns]
        
        # Add the state name as a new column to the DataFrame
        df['state'] = state_name
        
        # Append the DataFrame to the list
        dfs.append(df)

In [121]:
median_earnings = pd.concat(dfs, ignore_index=True)

In [122]:
len(median_earnings.state.unique())

50

In [125]:
median_earnings.columns = ['Label', 'Median earnings', 'Median earnings for male',
                          'Median earnings for female', 'Women\'s earnings as a percentage of men\'s earning',
                          'state']

In [128]:
median_earnings = median_earnings[median_earnings.Label == 'Full-time, year-round civilian employed population 16 years and over with earnings']

In [130]:
median_earnings = median_earnings[['Median earnings for male', 'Median earnings for female', 'state']]

In [138]:
median_earnings.loc[median_earnings['state'] == 'Washington', 'state'] =  'Washington (state)'

/Users/anna.zemit/opt/anaconda3/envs/notebook/lib/python3.7/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/Users/anna.zemit/opt/anaconda3/envs/notebook/lib/python3.7/site-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [139]:
median_earnings

     Median earnings for male Median earnings for female               state
0                      63,639                     52,329              Hawaii
36                     55,041                     42,616       West Virginia
72                     60,111                     46,345             Indiana
108                    67,414                     56,020           Minnesota
144                    63,636                     52,154        Pennsylvania
180                    75,042                     63,833            Maryland
216                    53,768                     45,993          New Mexico
252                    62,192                     48,084        North Dakota
288                    61,551                     54,972             Vermont
324                    66,112                     53,350            Illinois
360                    59,256                     48,421            Nebraska
396                    56,016                     43,865      South Carolina
432                    54,036                     46,802              Nevada
468                    59,545                     45,757              Kansas
504                    76,926                     62,111  Washington (state)
540                    69,668                     60,990            New York
576                    75,429                     63,977         Connecticut
612                    63,323                     52,155            Delaware
648                    54,193                     45,942             Florida
684                    55,273                     44,761             Montana
720                    79,976                     67,222       Massachusetts
756                    55,015                     43,557            Kentucky
792                    62,640                     53,765              Oregon
828                    61,720                     49,903            Michigan
864                    53,190                     42,122            Oklahoma
900                    73,322                     55,206       New Hampshire
936                    61,412                     49,727           Wisconsin
972                    71,428                     57,067            Colorado
1008                   65,512                     47,907                Utah
1044                   58,144                     50,245             Arizona
1080                   60,969                     47,486             Wyoming
1116                   60,337                     48,330               Texas
1152                   56,983                     45,034            Missouri
1188                   56,318                     42,597               Idaho
1224                   56,038                     42,006             Alabama
1260                   56,371                     45,158        South Dakota
1296                   56,245                     42,044           Louisiana
1332                   56,210                     47,188      North Carolina
1368                   76,375                     63,414          New Jersey
1404                   69,932                     57,420              Alaska
1440                   71,398                     56,821            Virginia
1476                   51,143                     39,449         Mississippi
1512                   68,498                     56,889        Rhode Island
1548                   60,101                     48,331                Iowa
1584                   51,383                     41,205            Arkansas
1620                   55,437                     45,150           Tennessee
1656                   67,700                     59,731          California
1692                   60,691                     49,069                Ohio
1728                   59,367                     49,925               Maine
1764                   59,870                     48,581             Georgia

## Subtract the cost of living for each state from each gender’s median earnings to calculate the estimated yearly savings for each gender in each state.

In [141]:
median_earnings = median_earnings.merge(living_cost, on=['state'], how='left')

In [144]:
median_earnings['Median earnings for male'] = median_earnings['Median earnings for male'].apply(lambda x: int(x.replace(',', '')))

In [145]:
median_earnings['Median earnings for female'] = median_earnings['Median earnings for female'].apply(lambda x: int(x.replace(',', '')))

In [146]:
median_earnings['Estimated_yearly_savings_Male'] = median_earnings['Median earnings for male'] - median_earnings['Required annual income before taxes']

In [148]:
median_earnings['Estimated_yearly_savings_Female'] = median_earnings['Median earnings for female'] - median_earnings['Required annual income before taxes']

In [149]:
median_earnings

,Median earnings for male,Median earnings for female,state,Required annual income before taxes,Estimated_yearly_savings_Male,Estimated_yearly_savings_Female
0,63639,52329,Hawaii,56841,6798,-4512
1,55041,42616,West Virginia,39386,15655,3230
2,60111,46345,Indiana,42510,17601,3835
3,67414,56020,Minnesota,44626,22788,11394
4,63636,52154,Pennsylvania,45661,17975,6493
5,75042,63833,Maryland,51460,23582,12373
6,53768,45993,New Mexico,41807,11961,4186
7,62192,48084,North Dakota,40262,21930,7822
8,61551,54972,Vermont,47892,13659,7080
9,66112,53350,Illinois,47559,18553,5791
10,59256,48421,Nebraska,41849,17407,6572
11,56016,43865,South Carolina,44152,11864,-287
12,54036,46802,Nevada,46727,7309,75
13,59545,45757,Kansas,42337,17208,3420
14,76926,62111,Washington (state),53242,23684,8869
15,69668,60990,New York,55878,13790,5112
16,75429,63977,Connecticut,50194,25235,13783
17,63323,52155,Delaware,47064,16259,5091
18,54193,45942,Florida,46645,7548,-703
19,55273,44761,Montana,42374,12899,2387
20,79976,67222,Massachusetts,58009,21967,9213
21,55015,43557,Kentucky,40355,14660,3202
22,62640,53765,Oregon,50553,12087,3212
23,61720,49903,Michigan,42187,19533,7716
24,53190,42122,Oklahoma,40211,12979,1911
25,73322,55206,New Hampshire,49045,24277,6161
26,61412,49727,Wisconsin,42062,19350,7665
27,71428,57067,Colorado,51644,19784,5423
28,65512,47907,Utah,46850,18662,1057
29,58144,50245,Arizona,48677,9467,1568
30,60969,47486,Wyoming,43823,17146,3663
31,60337,48330,Texas,43508,16829,4822
32,56983,45034,Missouri,42024,14959,3010
33,56318,42597,Idaho,44366,11952,-1769
34,56038,42006,Alabama,41911,14127,95
35,56371,45158,South Dakota,40718,15653,4440
36,56245,42044,Louisiana,41233,15012,811
37,56210,47188,North Carolina,44848,11362,2340
38,76375,63414,New Jersey,51504,24871,11910
39,69932,57420,Alaska,48375,21557,9045
40,71398,56821,Virginia,49973,21425,6848
41,51143,39449,Mississippi,41361,9782,-1912
42,68498,56889,Rhode Island,50418,18080,6471
43,60101,48331,Iowa,41678,18423,6653
44,51383,41205,Arkansas,39724,11659,1481
45,55437,45150,Tennessee,43196,12241,1954
46,67700,59731,California,56825,10875,2906
47,60691,49069,Ohio,40359,20332,8710
48,59367,49925,Maine,45844,13523,4081
49,59870,48581,Georgia,48448,11422,133

## Calculate how many years each gender would need to work to save for the comfortable retirement

In [155]:
df = life_expectancies.merge(median_earnings, on=['state'], how='left')

In [157]:
df['Years_Worked_for_Retirement_Male'] = df['Savings_Male']/df['Estimated_yearly_savings_Male']

In [159]:
df['Years_Worked_for_Retirement_Female'] = df['Savings_Female']/df['Estimated_yearly_savings_Female']

In [162]:
df.columns = ['state', 'males_life_expectation', 'females_life_expectation', 
              'Years_After_Retirement_Male','Years_After_Retirement_Female',
       'Required annual income before taxes * 20%', 'Savings_Male',
       'Savings_Female', 'Extra_Savings_for_Women', 'Median earnings for male',
       'Median earnings for female', 'Required annual income before taxes',
       'Estimated_yearly_savings_Male', 'Estimated_yearly_savings_Female',
       'Years_Worked_for_Retirement_Male',
       'Years_Worked_for_Retirement_Female']

In [163]:
df

,state,males_life_expectation,females_life_expectation,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes * 20%,Savings_Male,Savings_Female,Extra_Savings_for_Women,Median earnings for male,Median earnings for female,Required annual income before taxes,Estimated_yearly_savings_Male,Estimated_yearly_savings_Female,Years_Worked_for_Retirement_Male,Years_Worked_for_Retirement_Female
0,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00,395502.00,67700,59731,56825,10875,2906,76.498207,422.374398
1,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16,422897.04,63639,52329,56841,6798,-4512,136.458535,-299.322287
2,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12,395616.24,69668,60990,55878,13790,5112,52.514785,219.052254
3,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88,246335.52,67414,56020,44626,22788,11394,30.079663,81.779084
4,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00,355015.08,79976,67222,58009,21967,9213,39.294119,132.225008
5,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44,343326.96,75429,63977,50194,25235,13783,27.687754,75.602368
6,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20,364648.32,76375,63414,51504,24871,11910,26.341156,85.623778
7,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04,300284.88,76926,62111,53242,23684,8869,34.799281,126.786677
8,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32,316061.28,71428,57067,51644,19784,5423,36.963154,193.129323
9,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96,304593.12,61551,54972,47892,13659,7080,50.910890,141.240814
10,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00,219258.00,65512,47907,46850,18662,1057,38.259243,882.925260
11,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28,303318.00,62640,53765,50553,12087,3212,61.732628,326.737323
12,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56,250224.24,56318,42597,44366,11952,-1769,53.898454,-505.606874
13,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04,326708.64,68498,56889,50418,18080,6471,38.482765,158.009124
14,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00,294270.00,73322,55206,49045,24277,6161,30.303374,167.171725
15,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72,257419.44,61412,49727,42062,19350,7665,29.215157,107.336297
16,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44,256115.88,59256,48421,41849,17407,6572,32.311746,124.553628
17,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36,299838.00,71398,56821,49973,21425,6848,31.068395,140.986910
18,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96,260070.72,60101,48331,41678,18423,6653,29.590633,121.030957
19,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64,342424.80,66112,53350,47559,18553,5791,30.145736,155.710351
20,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00,330246.60,54193,45942,46645,7548,-703,78.606836,-1313.756757
21,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40,280223.52,62192,48084,40262,21930,7822,22.471814,98.827717
22,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20,356315.64,58144,50245,48677,9467,1568,57.999003,577.418495
23,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88,292373.76,60337,48330,43508,16829,4822,30.092883,165.658830
24,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40,364336.80,75042,63833,51460,23582,12373,25.662353,78.356615
25,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28,274583.52,55273,44761,42374,12899,2387,40.209145,332.317252
26,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64,254080.32,56371,45158,40718,15653,4440,31.839796,169.474919
27,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76,319074.24,59367,49925,45844,13523,4081,44.342196,225.119765
28,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92,306841.92,63636,52154,45661,17975,6493,30.483004,131.645452
29,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88,274343.76,59545,45757,42337,17208,3420,28.933236,225.797333
30,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40,316270.08,63323,52155,47064,16259,5091,34.388358,171.948615
31,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48,319612.68,54036,46802,46727,7309,75,72.881078,11364.006400
32,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12,273371.76,61720,49903,42187,19533,7716,24.362328,97.102271
33,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00,284445.00,69932,57420,48375,21557,9045,27.736466,97.552239
34,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24,257679.24,60969,47486,43823,17146,3663,30.670477,213.910794
35,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00,306760.32,56210,47188,44848,11362,2340,44.050667,344.984615
36,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68,319756.80,59870,48581,48448,11422,133,44.791707,6250.884812
37,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80,285667.20,60111,46345,42510,17601,3835,24.055429,184.893559
38,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28,271212.48,60691,49069,40359,20332,8710,20.246990,78.401180
39,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08,302572.80,56983,45034,42024,14959,3010,27.306189,236.227934
40,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92,326094.60,53768,45993,41807,11961,4186,30.618621,165.390330
41,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60,333789.12,56016,43865,44152,11864,-287,34.386757,-2584.507317
42,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28,260567.28,53190,42122,40211,12979,1911,27.883427,325.728038
43,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88,262178.40,51383,41205,39724,11659,1481,29.028946,405.554949
44,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04,321617.40,56245,42044,41233,15012,811,19.446419,756.531492
45,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60,326561.76,55437,45150,43196,12241,1954,28.371525,344.860594
46,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00,285713.40,55015,43557,40355,14660,3202,21.801610,189.045909
47,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68,316847.16,56038,42006,41911,14127,95,21.716466,6564.586105
48,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72,297758.16,55041,42616,39386,15655,3230,17.510480,177.054093
49,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84,327579.12,51143,39449,41361,9782,-1912,23.340086,-290.738410

# Finalise the data into tabs

## States Map - Savings

Rank all states based on the extra money that women need to save.

In [165]:
States_Map_Savings = df.sort_values(by=['Extra_Savings_for_Women'], ascending=False)

In [166]:
States_Map_Savings

,state,males_life_expectation,females_life_expectation,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes * 20%,Savings_Male,Savings_Female,Extra_Savings_for_Women,Median earnings for male,Median earnings for female,Required annual income before taxes,Estimated_yearly_savings_Male,Estimated_yearly_savings_Female,Years_Worked_for_Retirement_Male,Years_Worked_for_Retirement_Female
1,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16,422897.04,63639,52329,56841,6798,-4512,136.458535,-299.322287
2,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12,395616.24,69668,60990,55878,13790,5112,52.514785,219.052254
0,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00,395502.00,67700,59731,56825,10875,2906,76.498207,422.374398
6,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20,364648.32,76375,63414,51504,24871,11910,26.341156,85.623778
24,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40,364336.80,75042,63833,51460,23582,12373,25.662353,78.356615
22,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20,356315.64,58144,50245,48677,9467,1568,57.999003,577.418495
4,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00,355015.08,79976,67222,58009,21967,9213,39.294119,132.225008
5,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44,343326.96,75429,63977,50194,25235,13783,27.687754,75.602368
19,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64,342424.80,66112,53350,47559,18553,5791,30.145736,155.710351
41,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60,333789.12,56016,43865,44152,11864,-287,34.386757,-2584.507317
20,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00,330246.60,54193,45942,46645,7548,-703,78.606836,-1313.756757
49,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84,327579.12,51143,39449,41361,9782,-1912,23.340086,-290.738410
13,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04,326708.64,68498,56889,50418,18080,6471,38.482765,158.009124
45,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60,326561.76,55437,45150,43196,12241,1954,28.371525,344.860594
40,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92,326094.60,53768,45993,41807,11961,4186,30.618621,165.390330
44,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04,321617.40,56245,42044,41233,15012,811,19.446419,756.531492
36,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68,319756.80,59870,48581,48448,11422,133,44.791707,6250.884812
31,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48,319612.68,54036,46802,46727,7309,75,72.881078,11364.006400
27,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76,319074.24,59367,49925,45844,13523,4081,44.342196,225.119765
47,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68,316847.16,56038,42006,41911,14127,95,21.716466,6564.586105
30,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40,316270.08,63323,52155,47064,16259,5091,34.388358,171.948615
8,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32,316061.28,71428,57067,51644,19784,5423,36.963154,193.129323
28,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92,306841.92,63636,52154,45661,17975,6493,30.483004,131.645452
35,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00,306760.32,56210,47188,44848,11362,2340,44.050667,344.984615
9,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96,304593.12,61551,54972,47892,13659,7080,50.910890,141.240814
11,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28,303318.00,62640,53765,50553,12087,3212,61.732628,326.737323
39,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08,302572.80,56983,45034,42024,14959,3010,27.306189,236.227934
7,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04,300284.88,76926,62111,53242,23684,8869,34.799281,126.786677
17,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36,299838.00,71398,56821,49973,21425,6848,31.068395,140.986910
48,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72,297758.16,55041,42616,39386,15655,3230,17.510480,177.054093
14,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00,294270.00,73322,55206,49045,24277,6161,30.303374,167.171725
23,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88,292373.76,60337,48330,43508,16829,4822,30.092883,165.658830
46,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00,285713.40,55015,43557,40355,14660,3202,21.801610,189.045909
37,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80,285667.20,60111,46345,42510,17601,3835,24.055429,184.893559
33,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00,284445.00,69932,57420,48375,21557,9045,27.736466,97.552239
21,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40,280223.52,62192,48084,40262,21930,7822,22.471814,98.827717
25,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28,274583.52,55273,44761,42374,12899,2387,40.209145,332.317252
29,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88,274343.76,59545,45757,42337,17208,3420,28.933236,225.797333
32,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12,273371.76,61720,49903,42187,19533,7716,24.362328,97.102271
38,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28,271212.48,60691,49069,40359,20332,8710,20.246990,78.401180
43,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88,262178.40,51383,41205,39724,11659,1481,29.028946,405.554949
42,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28,260567.28,53190,42122,40211,12979,1911,27.883427,325.728038
18,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96,260070.72,60101,48331,41678,18423,6653,29.590633,121.030957
34,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24,257679.24,60969,47486,43823,17146,3663,30.670477,213.910794
15,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72,257419.44,61412,49727,42062,19350,7665,29.215157,107.336297
16,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44,256115.88,59256,48421,41849,17407,6572,32.311746,124.553628
26,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64,254080.32,56371,45158,40718,15653,4440,31.839796,169.474919
12,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56,250224.24,56318,42597,44366,11952,-1769,53.898454,-505.606874
3,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88,246335.52,67414,56020,44626,22788,11394,30.079663,81.779084
10,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00,219258.00,65512,47907,46850,18662,1057,38.259243,882.925260

## Table - Savings

All data for all states, with columns for men savings, women savings and the difference.

In [167]:
table_savings = df.copy()

In [168]:
table_savings

,state,males_life_expectation,females_life_expectation,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes * 20%,Savings_Male,Savings_Female,Extra_Savings_for_Women,Median earnings for male,Median earnings for female,Required annual income before taxes,Estimated_yearly_savings_Male,Estimated_yearly_savings_Female,Years_Worked_for_Retirement_Male,Years_Worked_for_Retirement_Female
0,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00,395502.00,67700,59731,56825,10875,2906,76.498207,422.374398
1,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16,422897.04,63639,52329,56841,6798,-4512,136.458535,-299.322287
2,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12,395616.24,69668,60990,55878,13790,5112,52.514785,219.052254
3,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88,246335.52,67414,56020,44626,22788,11394,30.079663,81.779084
4,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00,355015.08,79976,67222,58009,21967,9213,39.294119,132.225008
5,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44,343326.96,75429,63977,50194,25235,13783,27.687754,75.602368
6,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20,364648.32,76375,63414,51504,24871,11910,26.341156,85.623778
7,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04,300284.88,76926,62111,53242,23684,8869,34.799281,126.786677
8,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32,316061.28,71428,57067,51644,19784,5423,36.963154,193.129323
9,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96,304593.12,61551,54972,47892,13659,7080,50.910890,141.240814
10,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00,219258.00,65512,47907,46850,18662,1057,38.259243,882.925260
11,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28,303318.00,62640,53765,50553,12087,3212,61.732628,326.737323
12,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56,250224.24,56318,42597,44366,11952,-1769,53.898454,-505.606874
13,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04,326708.64,68498,56889,50418,18080,6471,38.482765,158.009124
14,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00,294270.00,73322,55206,49045,24277,6161,30.303374,167.171725
15,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72,257419.44,61412,49727,42062,19350,7665,29.215157,107.336297
16,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44,256115.88,59256,48421,41849,17407,6572,32.311746,124.553628
17,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36,299838.00,71398,56821,49973,21425,6848,31.068395,140.986910
18,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96,260070.72,60101,48331,41678,18423,6653,29.590633,121.030957
19,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64,342424.80,66112,53350,47559,18553,5791,30.145736,155.710351
20,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00,330246.60,54193,45942,46645,7548,-703,78.606836,-1313.756757
21,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40,280223.52,62192,48084,40262,21930,7822,22.471814,98.827717
22,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20,356315.64,58144,50245,48677,9467,1568,57.999003,577.418495
23,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88,292373.76,60337,48330,43508,16829,4822,30.092883,165.658830
24,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40,364336.80,75042,63833,51460,23582,12373,25.662353,78.356615
25,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28,274583.52,55273,44761,42374,12899,2387,40.209145,332.317252
26,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64,254080.32,56371,45158,40718,15653,4440,31.839796,169.474919
27,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76,319074.24,59367,49925,45844,13523,4081,44.342196,225.119765
28,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92,306841.92,63636,52154,45661,17975,6493,30.483004,131.645452
29,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88,274343.76,59545,45757,42337,17208,3420,28.933236,225.797333
30,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40,316270.08,63323,52155,47064,16259,5091,34.388358,171.948615
31,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48,319612.68,54036,46802,46727,7309,75,72.881078,11364.006400
32,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12,273371.76,61720,49903,42187,19533,7716,24.362328,97.102271
33,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00,284445.00,69932,57420,48375,21557,9045,27.736466,97.552239
34,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24,257679.24,60969,47486,43823,17146,3663,30.670477,213.910794
35,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00,306760.32,56210,47188,44848,11362,2340,44.050667,344.984615
36,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68,319756.80,59870,48581,48448,11422,133,44.791707,6250.884812
37,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80,285667.20,60111,46345,42510,17601,3835,24.055429,184.893559
38,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28,271212.48,60691,49069,40359,20332,8710,20.246990,78.401180
39,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08,302572.80,56983,45034,42024,14959,3010,27.306189,236.227934
40,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92,326094.60,53768,45993,41807,11961,4186,30.618621,165.390330
41,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60,333789.12,56016,43865,44152,11864,-287,34.386757,-2584.507317
42,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28,260567.28,53190,42122,40211,12979,1911,27.883427,325.728038
43,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88,262178.40,51383,41205,39724,11659,1481,29.028946,405.554949
44,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04,321617.40,56245,42044,41233,15012,811,19.446419,756.531492
45,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60,326561.76,55437,45150,43196,12241,1954,28.371525,344.860594
46,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00,285713.40,55015,43557,40355,14660,3202,21.801610,189.045909
47,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68,316847.16,56038,42006,41911,14127,95,21.716466,6564.586105
48,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72,297758.16,55041,42616,39386,15655,3230,17.510480,177.054093
49,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84,327579.12,51143,39449,41361,9782,-1912,23.340086,-290.738410

## States Map - Years

States Map - Years: rank all states based on the extra years women need to work.

In [169]:
States_Map_Years = df.sort_values(by=['Years_Worked_for_Retirement_Female'], ascending=False)

In [170]:
States_Map_Years

,state,males_life_expectation,females_life_expectation,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes * 20%,Savings_Male,Savings_Female,Extra_Savings_for_Women,Median earnings for male,Median earnings for female,Required annual income before taxes,Estimated_yearly_savings_Male,Estimated_yearly_savings_Female,Years_Worked_for_Retirement_Male,Years_Worked_for_Retirement_Female
31,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48,319612.68,54036,46802,46727,7309,75,72.881078,11364.006400
47,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68,316847.16,56038,42006,41911,14127,95,21.716466,6564.586105
36,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68,319756.80,59870,48581,48448,11422,133,44.791707,6250.884812
10,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00,219258.00,65512,47907,46850,18662,1057,38.259243,882.925260
44,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04,321617.40,56245,42044,41233,15012,811,19.446419,756.531492
22,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20,356315.64,58144,50245,48677,9467,1568,57.999003,577.418495
0,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00,395502.00,67700,59731,56825,10875,2906,76.498207,422.374398
43,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88,262178.40,51383,41205,39724,11659,1481,29.028946,405.554949
35,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00,306760.32,56210,47188,44848,11362,2340,44.050667,344.984615
45,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60,326561.76,55437,45150,43196,12241,1954,28.371525,344.860594
25,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28,274583.52,55273,44761,42374,12899,2387,40.209145,332.317252
11,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28,303318.00,62640,53765,50553,12087,3212,61.732628,326.737323
42,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28,260567.28,53190,42122,40211,12979,1911,27.883427,325.728038
39,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08,302572.80,56983,45034,42024,14959,3010,27.306189,236.227934
29,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88,274343.76,59545,45757,42337,17208,3420,28.933236,225.797333
27,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76,319074.24,59367,49925,45844,13523,4081,44.342196,225.119765
2,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12,395616.24,69668,60990,55878,13790,5112,52.514785,219.052254
34,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24,257679.24,60969,47486,43823,17146,3663,30.670477,213.910794
8,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32,316061.28,71428,57067,51644,19784,5423,36.963154,193.129323
46,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00,285713.40,55015,43557,40355,14660,3202,21.801610,189.045909
37,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80,285667.20,60111,46345,42510,17601,3835,24.055429,184.893559
48,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72,297758.16,55041,42616,39386,15655,3230,17.510480,177.054093
30,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40,316270.08,63323,52155,47064,16259,5091,34.388358,171.948615
26,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64,254080.32,56371,45158,40718,15653,4440,31.839796,169.474919
14,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00,294270.00,73322,55206,49045,24277,6161,30.303374,167.171725
23,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88,292373.76,60337,48330,43508,16829,4822,30.092883,165.658830
40,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92,326094.60,53768,45993,41807,11961,4186,30.618621,165.390330
13,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04,326708.64,68498,56889,50418,18080,6471,38.482765,158.009124
19,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64,342424.80,66112,53350,47559,18553,5791,30.145736,155.710351
9,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96,304593.12,61551,54972,47892,13659,7080,50.910890,141.240814
17,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36,299838.00,71398,56821,49973,21425,6848,31.068395,140.986910
4,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00,355015.08,79976,67222,58009,21967,9213,39.294119,132.225008
28,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92,306841.92,63636,52154,45661,17975,6493,30.483004,131.645452
7,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04,300284.88,76926,62111,53242,23684,8869,34.799281,126.786677
16,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44,256115.88,59256,48421,41849,17407,6572,32.311746,124.553628
18,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96,260070.72,60101,48331,41678,18423,6653,29.590633,121.030957
15,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72,257419.44,61412,49727,42062,19350,7665,29.215157,107.336297
21,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40,280223.52,62192,48084,40262,21930,7822,22.471814,98.827717
33,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00,284445.00,69932,57420,48375,21557,9045,27.736466,97.552239
32,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12,273371.76,61720,49903,42187,19533,7716,24.362328,97.102271
6,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20,364648.32,76375,63414,51504,24871,11910,26.341156,85.623778
3,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88,246335.52,67414,56020,44626,22788,11394,30.079663,81.779084
38,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28,271212.48,60691,49069,40359,20332,8710,20.246990,78.401180
24,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40,364336.80,75042,63833,51460,23582,12373,25.662353,78.356615
5,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44,343326.96,75429,63977,50194,25235,13783,27.687754,75.602368
49,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84,327579.12,51143,39449,41361,9782,-1912,23.340086,-290.738410
1,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16,422897.04,63639,52329,56841,6798,-4512,136.458535,-299.322287
12,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56,250224.24,56318,42597,44366,11952,-1769,53.898454,-505.606874
20,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00,330246.60,54193,45942,46645,7548,-703,78.606836,-1313.756757
41,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60,333789.12,56016,43865,44152,11864,-287,34.386757,-2584.507317

## Table - Years

Table - Years: all data for all states, with columns for men years, women years and the difference.

In [171]:
Table_Years = df.copy()

In [172]:
Table_Years['Extra_Years_for_Women'] = Table_Years['Years_Worked_for_Retirement_Female'] - Table_Years['Years_Worked_for_Retirement_Male']

In [173]:
Table_Years

,state,males_life_expectation,females_life_expectation,Years_After_Retirement_Male,Years_After_Retirement_Female,Required annual income before taxes * 20%,Savings_Male,Savings_Female,Extra_Savings_for_Women,Median earnings for male,Median earnings for female,Required annual income before taxes,Estimated_yearly_savings_Male,Estimated_yearly_savings_Female,Years_Worked_for_Retirement_Male,Years_Worked_for_Retirement_Female,Extra_Years_for_Women
0,California,76.2,82.0,12.2,18.0,68190.0,831918.00,1227420.00,395502.00,67700,59731,56825,10875,2906,76.498207,422.374398,345.876191
1,Hawaii,77.6,83.8,13.6,19.8,68209.2,927645.12,1350542.16,422897.04,63639,52329,56841,6798,-4512,136.458535,-299.322287,-435.780822
2,New York,74.8,80.7,10.8,16.7,67053.6,724178.88,1119795.12,395616.24,69668,60990,55878,13790,5112,52.514785,219.052254,166.537469
3,Minnesota,76.8,81.4,12.8,17.4,53551.2,685455.36,931790.88,246335.52,67414,56020,44626,22788,11394,30.079663,81.779084,51.699421
4,Massachusetts,76.4,81.5,12.4,17.5,69610.8,863173.92,1218189.00,355015.08,79976,67222,58009,21967,9213,39.294119,132.225008,92.930889
5,Connecticut,75.6,81.3,11.6,17.3,60232.8,698700.48,1042027.44,343326.96,75429,63977,50194,25235,13783,27.687754,75.602368,47.914614
6,New Jersey,74.6,80.5,10.6,16.5,61804.8,655130.88,1019779.20,364648.32,76375,63414,51504,24871,11910,26.341156,85.623778,59.282623
7,Washington (state),76.9,81.6,12.9,17.6,63890.4,824186.16,1124471.04,300284.88,76926,62111,53242,23684,8869,34.799281,126.786677,91.987397
8,Colorado,75.8,80.9,11.8,16.9,61972.8,731279.04,1047340.32,316061.28,71428,57067,51644,19784,5423,36.963154,193.129323,156.166169
9,Vermont,76.1,81.4,12.1,17.4,57470.4,695391.84,999984.96,304593.12,61551,54972,47892,13659,7080,50.910890,141.240814,90.329924
10,Utah,76.7,80.6,12.7,16.6,56220.0,713994.00,933252.00,219258.00,65512,47907,46850,18662,1057,38.259243,882.925260,844.666017
11,Oregon,76.3,81.3,12.3,17.3,60663.6,746162.28,1049480.28,303318.00,62640,53765,50553,12087,3212,61.732628,326.737323,265.004694
12,Idaho,76.1,80.8,12.1,16.8,53239.2,644194.32,894418.56,250224.24,56318,42597,44366,11952,-1769,53.898454,-505.606874,-559.505328
13,Rhode Island,75.5,80.9,11.5,16.9,60501.6,695768.40,1022477.04,326708.64,68498,56889,50418,18080,6471,38.482765,158.009124,119.526358
14,New Hampshire,76.5,81.5,12.5,17.5,58854.0,735675.00,1029945.00,294270.00,73322,55206,49045,24277,6161,30.303374,167.171725,136.868352
15,Wisconsin,75.2,80.3,11.2,16.3,50474.4,565313.28,822732.72,257419.44,61412,49727,42062,19350,7665,29.215157,107.336297,78.121141
16,Nebraska,75.2,80.3,11.2,16.3,50218.8,562450.56,818566.44,256115.88,59256,48421,41849,17407,6572,32.311746,124.553628,92.241882
17,Virginia,75.1,80.1,11.1,16.1,59967.6,665640.36,965478.36,299838.00,71398,56821,49973,21425,6848,31.068395,140.986910,109.918515
18,Iowa,74.9,80.1,10.9,16.1,50013.6,545148.24,805218.96,260070.72,60101,48331,41678,18423,6653,29.590633,121.030957,91.440324
19,Illinois,73.8,79.8,9.8,15.8,57070.8,559293.84,901718.64,342424.80,66112,53350,47559,18553,5791,30.145736,155.710351,125.564615
20,Florida,74.6,80.5,10.6,16.5,55974.0,593324.40,923571.00,330246.60,54193,45942,46645,7548,-703,78.606836,-1313.756757,-1392.363593
21,North Dakota,74.2,80.0,10.2,16.0,48314.4,492806.88,773030.40,280223.52,62192,48084,40262,21930,7822,22.471814,98.827717,76.355903
22,Arizona,73.4,79.5,9.4,15.5,58412.4,549076.56,905392.20,356315.64,58144,50245,48677,9467,1568,57.999003,577.418495,519.419492
23,Texas,73.7,79.3,9.7,15.3,52209.6,506433.12,798806.88,292373.76,60337,48330,43508,16829,4822,30.092883,165.658830,135.565948
24,Maryland,73.8,79.7,9.8,15.7,61752.0,605169.60,969506.40,364336.80,75042,63833,51460,23582,12373,25.662353,78.356615,52.694263
25,Montana,74.2,79.6,10.2,15.6,50848.8,518657.76,793241.28,274583.52,55273,44761,42374,12899,2387,40.209145,332.317252,292.108107
26,South Dakota,74.2,79.4,10.2,15.4,48861.6,498388.32,752468.64,254080.32,56371,45158,40718,15653,4440,31.839796,169.474919,137.635123
27,Maine,74.9,80.7,10.9,16.7,55012.8,599639.52,918713.76,319074.24,59367,49925,45844,13523,4081,44.342196,225.119765,180.777569
28,Pennsylvania,74.0,79.6,10.0,15.6,54793.2,547932.00,854773.92,306841.92,63636,52154,45661,17975,6493,30.483004,131.645452,101.162448
29,Kansas,73.8,79.2,9.8,15.2,50804.4,497883.12,772226.88,274343.76,59545,45757,42337,17208,3420,28.933236,225.797333,196.864098
30,Delaware,73.9,79.5,9.9,15.5,56476.8,559120.32,875390.40,316270.08,63323,52155,47064,16259,5091,34.388358,171.948615,137.560257
31,Nevada,73.5,79.2,9.5,15.2,56072.4,532687.80,852300.48,319612.68,54036,46802,46727,7309,75,72.881078,11364.006400,11291.125322
32,Michigan,73.4,78.8,9.4,14.8,50624.4,475869.36,749241.12,273371.76,61720,49903,42187,19533,7716,24.362328,97.102271,72.739942
33,Alaska,74.3,79.2,10.3,15.2,58050.0,597915.00,882360.00,284445.00,69932,57420,48375,21557,9045,27.736466,97.552239,69.815773
34,Wyoming,74.0,78.9,10.0,14.9,52587.6,525876.00,783555.24,257679.24,60969,47486,43823,17146,3663,30.670477,213.910794,183.240317
35,North Carolina,73.3,79.0,9.3,15.0,53817.6,500503.68,807264.00,306760.32,56210,47188,44848,11362,2340,44.050667,344.984615,300.933948
36,Georgia,72.8,78.3,8.8,14.3,58137.6,511610.88,831367.68,319756.80,59870,48581,48448,11422,133,44.791707,6250.884812,6206.093105
37,Indiana,72.3,77.9,8.3,13.9,51012.0,423399.60,709066.80,285667.20,60111,46345,42510,17601,3835,24.055429,184.893559,160.838131
38,Ohio,72.5,78.1,8.5,14.1,48430.8,411661.80,682874.28,271212.48,60691,49069,40359,20332,8710,20.246990,78.401180,58.154190
39,Missouri,72.1,78.1,8.1,14.1,50428.8,408473.28,711046.08,302572.80,56983,45034,42024,14959,3010,27.306189,236.227934,208.921745
40,New Mexico,71.3,77.8,7.3,13.8,50168.4,366229.32,692323.92,326094.60,53768,45993,41807,11961,4186,30.618621,165.390330,134.771709
41,South Carolina,71.7,78.0,7.7,14.0,52982.4,407964.48,741753.60,333789.12,56016,43865,44152,11864,-287,34.386757,-2584.507317,-2618.894074
42,Oklahoma,71.5,76.9,7.5,12.9,48253.2,361899.00,622466.28,260567.28,53190,42122,40211,12979,1911,27.883427,325.728038,297.844611
43,Arkansas,71.1,76.6,7.1,12.6,47668.8,338448.48,600626.88,262178.40,51383,41205,39724,11659,1481,29.028946,405.554949,376.526003
44,Louisiana,69.9,76.4,5.9,12.4,49479.6,291929.64,613547.04,321617.40,56245,42044,41233,15012,811,19.446419,756.531492,737.085073
45,Tennessee,70.7,77.0,6.7,13.0,51835.2,347295.84,673857.60,326561.76,55437,45150,43196,12241,1954,28.371525,344.860594,316.489068
46,Kentucky,70.6,76.5,6.6,12.5,48426.0,319611.60,605325.00,285713.40,55015,43557,40355,14660,3202,21.801610,189.045909,167.244299
47,Alabama,70.1,76.4,6.1,12.4,50293.2,306788.52,623635.68,316847.16,56038,42006,41911,14127,95,21.716466,6564.586105,6542.869639
48,West Virginia,69.8,76.1,5.8,12.1,47263.2,274126.56,571884.72,297758.16,55041,42616,39386,15655,3230,17.510480,177.054093,159.543613
49,Mississippi,68.6,75.2,4.6,11.2,49633.2,228312.72,555891.84,327579.12,51143,39449,41361,9782,-1912,23.340086,-290.738410,-314.078496

# Create an Excel file

In [174]:
# Create an Excel writer object

writer = pd.ExcelWriter('How Much More Do Women Need to Save For A Comfortable Retirement?.xlsx')

In [175]:
States_Map_Savings.to_excel(writer, sheet_name='States Map Savings', index=False)
table_savings.to_excel(writer, sheet_name='Table Savings', index=False)
States_Map_Years.to_excel(writer, sheet_name='States Map Years', index=False)
Table_Years.to_excel(writer, sheet_name='Table Years', index=False)

In [176]:
# Save the Excel file
writer.save()